import * as THREE from '/modules/three.module.js';
import { CSS3DRenderer, CSS3DObject } from "/modules/CSS3DRenderer.js";

class SoundStation {
    constructor(scene, name, label_meshes) {
        this.scene = scene
        this.mesh = null
        this.light = null;
        this.name = name
        this.isPlaying = false;
        this.label_meshes = label_meshes
        this.isLit = false;



    }
    createCylinder(_x, _y, _z, _rotation) {
        let mat = new THREE.MeshPhongMaterial({
            wireframe: true,
            transparent: false,
            depthWrite: true,
            side: THREE.DoubleSide,
            color: new THREE.Color(0xFFE778),
            emissive: new THREE.Color(0xC3A72A),
            emissiveIntensity: .2,
            opacity: 1,
        });
        let geo = new THREE.SphereGeometry(2, 2, 2, 1)
        let mesh = new THREE.Mesh(geo, mat)
        mesh.position.x = _x
        mesh.position.y = _y
        mesh.position.z = _z
        mesh.rotation.y = _rotation



        // mesh.add(light)
        this.mesh = mesh
        this.scene.add(mesh)

        // }
    }

    createFrame(htmlIdx, _x, _y, _z) {
        console.log("creating frame")
        let mat = new THREE.MeshBasicMaterial({
            transparent: true,
            opacity: 0
        });
        let geo = new THREE.BoxGeometry(.5, .5, .5)
        let mesh = new THREE.Mesh(geo, mat)
        mesh.position.x = _x
        mesh.position.y = _y
        mesh.position.z = _z

        var card_width = 600

        var sc_names = [
            `Kiss & Love & F*ck`,
            `Better off as asteroids`,
            'Satelite',
            "Fuckin' Lights On'",
            'Ice Cream Nightly',
            'EVIDENCE',
            'I know that I',
            'Colours of My Mind',
            'You With Me',
            'Feel It On My Own',
            'Birthday Cakes',
            'Engine Rev',

        ]
        // var html = [

        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1235918551&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/kiss-and-love-and-fck" title="Kiss &amp; Love &amp; F*ck" target="_blank" style="color: #cccccc; text-decoration: none;">Kiss &amp; Love &amp; F*ck</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1085210068&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/better-off-as-asteroids" title="Better off as asteroids" target="_blank" style="color: #cccccc; text-decoration: none;">Better off as asteroids</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836073&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/satelite" title="Satelite" target="_blank" style="color: #cccccc; text-decoration: none;">Satelite</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836052&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/fuckin-lights-on" title="Fuckin Lights On" target="_blank" style="color: #cccccc; text-decoration: none;">Fuckin Lights On</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/904725760&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/ice-cream-nightly" title="Ice Cream Nightly" target="_blank" style="color: #cccccc; text-decoration: none;">Ice Cream Nightly</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910839499&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/evidence" title="EVIDENCE" target="_blank" style="color: #cccccc; text-decoration: none;">EVIDENCE</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836043&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/i-know-that-i" title="I Know That I" target="_blank" style="color: #cccccc; text-decoration: none;">I Know That I</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836007&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/colours-of-my-mind" title="Colours of My Mind" target="_blank" style="color: #cccccc; text-decoration: none;">Colours of My Mind</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910835983&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/you-with-me" title="You with Me" target="_blank" style="color: #cccccc; text-decoration: none;">You with Me</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836016&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/feel-it-on-my-own" title="Feel It On My Own&#x27;" target="_blank" style="color: #cccccc; text-decoration: none;">Feel It On My Own&#x27;</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836028&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/birthday-cakes" title="Birthday Cakes" target="_blank" style="color: #cccccc; text-decoration: none;">Birthday Cakes</a></div>`,
        //     `<iframe width="${card_width}" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910835995&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/engine-rev" title="Engine Rev" target="_blank" style="color: #cccccc; text-decoration: none;">Engine Rev</a></div>`,

        // ]
        var html = [
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1263695629&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/the-inferno" title="The Inferno" target="_blank" style="color: #cccccc; text-decoration: none;">The Inferno</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1243602520&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/my-crush" title="My Crush" target="_blank" style="color: #cccccc; text-decoration: none;">My Crush</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1235918551&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/kiss-and-love-and-fck" title="Kiss &amp; Love &amp; F*ck" target="_blank" style="color: #cccccc; text-decoration: none;">Kiss &amp; Love &amp; F*ck</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1227229414&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/dionysis-den" title="Dionysis Den" target="_blank" style="color: #cccccc; text-decoration: none;">Dionysis Den</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1218691315&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/do-i-have-adhd" title="Do I have ADHD?" target="_blank" style="color: #cccccc; text-decoration: none;">Do I have ADHD?</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1130714497&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/i-love-you-in-the-morning" title="I Love You In The Morning" target="_blank" style="color: #cccccc; text-decoration: none;">I Love You In The Morning</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1127563918&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/like-nobody-else-take" title="Like Nobody Else [take]" target="_blank" style="color: #cccccc; text-decoration: none;">Like Nobody Else [take]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1106486806&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/birthday-cakes-1" title="Birthday Cakes" target="_blank" style="color: #cccccc; text-decoration: none;">Birthday Cakes</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1085210068&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/better-off-as-asteroids" title="Better off as asteroids" target="_blank" style="color: #cccccc; text-decoration: none;">Better off as asteroids</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1077216484&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/something-i-cant-put-my-finger-on" title="Something I Cant Put My Finger On" target="_blank" style="color: #cccccc; text-decoration: none;">Something I Cant Put My Finger On</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1069312885&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/burnin-in-the-rhythm-of-the-night" title="Burnin&#x27; in the rhythm of the night" target="_blank" style="color: #cccccc; text-decoration: none;">Burnin&#x27; in the rhythm of the night</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1010034547&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/strings-to-my-guitar" title="Strings To My Guitar" target="_blank" style="color: #cccccc; text-decoration: none;">Strings To My Guitar</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/937794223&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/george-james-minecraft" title="George &amp; James (Minecraft)" target="_blank" style="color: #cccccc; text-decoration: none;">George &amp; James (Minecraft)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/933816184&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/hazmat-romance" title="Hazmat Romance" target="_blank" style="color: #cccccc; text-decoration: none;">Hazmat Romance</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/929517769&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/sunday" title="I can do a backflip" target="_blank" style="color: #cccccc; text-decoration: none;">I can do a backflip</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/929451928&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/saturday" title="Saturday" target="_blank" style="color: #cccccc; text-decoration: none;">Saturday</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/929415286&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/bags" title="Bags" target="_blank" style="color: #cccccc; text-decoration: none;">Bags</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/922409311&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/i-got-caught-up-in-the-movies" title="I Got Caught Up In The Movies" target="_blank" style="color: #cccccc; text-decoration: none;">I Got Caught Up In The Movies</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/904733848&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/frustrated" title="Frustrated" target="_blank" style="color: #cccccc; text-decoration: none;">Frustrated</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/892882468&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/you-dont-know-this-yet" title="You Don&#x27;t Know This Yet" target="_blank" style="color: #cccccc; text-decoration: none;">You Don&#x27;t Know This Yet</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/267738855&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/you-can-be-sure" title="You Can Be Sure" target="_blank" style="color: #cccccc; text-decoration: none;">You Can Be Sure</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/237590818&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/what-we-used-to-say-2" title="What We Used To Say" target="_blank" style="color: #cccccc; text-decoration: none;">What We Used To Say</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/239421467&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/living-tempo" title="Living Tempo" target="_blank" style="color: #cccccc; text-decoration: none;">Living Tempo</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/240260781&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/good-as-gone-heart-bandit" title="Good As Gone (Heart Bandit)" target="_blank" style="color: #cccccc; text-decoration: none;">Good As Gone (Heart Bandit)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/245783907&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/like-nobody-else-original" title="Like Nobody Else" target="_blank" style="color: #cccccc; text-decoration: none;">Like Nobody Else</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/249421722&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/colors-of-my-mind-final-mix-2-28-16" title="Colors Of My Mind" target="_blank" style="color: #cccccc; text-decoration: none;">Colors Of My Mind</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/254838473&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/onedirection" title="One Direction" target="_blank" style="color: #cccccc; text-decoration: none;">One Direction</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/255344731&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/james-fraser-in-talk" title="Talk" target="_blank" style="color: #cccccc; text-decoration: none;">Talk</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/257373282&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/tell-me-its-my-time-to-try" title="Tell Me It&#x27;s My Time (To Try)" target="_blank" style="color: #cccccc; text-decoration: none;">Tell Me It&#x27;s My Time (To Try)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/259846405&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/soft-me" title="Soft me" target="_blank" style="color: #cccccc; text-decoration: none;">Soft me</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/260726824&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/made-for-this" title="Made for this" target="_blank" style="color: #cccccc; text-decoration: none;">Made for this</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/261738791&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/hero" title="Hero - Enrique Iglesias (Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">Hero - Enrique Iglesias (Remix)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/262583094&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/fall-silenlty" title="Fall Silenlty" target="_blank" style="color: #cccccc; text-decoration: none;">Fall Silenlty</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/264830250&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/depleted" title="Depleted" target="_blank" style="color: #cccccc; text-decoration: none;">Depleted</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/272180775&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/sometimesihitmystride" title="Sometimes I hit my stride" target="_blank" style="color: #cccccc; text-decoration: none;">Sometimes I hit my stride</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/273419315&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/feelgood2max" title="Feel Good 2 Max" target="_blank" style="color: #cccccc; text-decoration: none;">Feel Good 2 Max</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/273419577&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/happycmax" title="Happy C Max" target="_blank" style="color: #cccccc; text-decoration: none;">Happy C Max</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/275111880&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/do-it-all" title="Do it all" target="_blank" style="color: #cccccc; text-decoration: none;">Do it all</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/291840877&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/everywehere-i-go" title="Everywehere I Go" target="_blank" style="color: #cccccc; text-decoration: none;">Everywehere I Go</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/277168931&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/ethinc" title="Ethnic" target="_blank" style="color: #cccccc; text-decoration: none;">Ethnic</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/872191351&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/fat-rats" title="fat rats love media, and govt&#x27;s too big" target="_blank" style="color: #cccccc; text-decoration: none;">fat rats love media, and govt&#x27;s too big</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/863557879&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/americas-body-count" title="America&#x27;s Body Count" target="_blank" style="color: #cccccc; text-decoration: none;">America&#x27;s Body Count</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/631216995&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/sycamore-trees" title="Sycamore Trees" target="_blank" style="color: #cccccc; text-decoration: none;">Sycamore Trees</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/292020125&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/chasing-my-ghost" title="Chasing My Ghost" target="_blank" style="color: #cccccc; text-decoration: none;">Chasing My Ghost</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/255009909&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/surf" title="James Fraser - Surf" target="_blank" style="color: #cccccc; text-decoration: none;">James Fraser - Surf</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/249093003&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/walls-and-windows" title="James Fraser - Walls and Windows" target="_blank" style="color: #cccccc; text-decoration: none;">James Fraser - Walls and Windows</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/232767430&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/foster-the-people-best-friend-james-fraser-remix-white-1" title="Foster The People - Best Friend (James Fraser Remix) [White]" target="_blank" style="color: #cccccc; text-decoration: none;">Foster The People - Best Friend (James Fraser Remix) [White]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/204471394&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/new-world-ft-evelynn-original-mix" title="New World Ft. Evelynn - [Original Mix]" target="_blank" style="color: #cccccc; text-decoration: none;">New World Ft. Evelynn - [Original Mix]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/204315629&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/with-you-ft-fmlybnd-saladfatt-remix-1" title="Dirty South ft. FMLYBND - With You (James Fraser REMIX)" target="_blank" style="color: #cccccc; text-decoration: none;">Dirty South ft. FMLYBND - With You (James Fraser REMIX)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/202709258&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/saladfatt-work-it-original-mix" title="Work It - (Original Mix)" target="_blank" style="color: #cccccc; text-decoration: none;">Work It - (Original Mix)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/199312982&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/call-a-doctor-original-mix-animal-house-mix" title="Call a doctor - (Original Mix) [~ANIMAL HOUSE MIX~]" target="_blank" style="color: #cccccc; text-decoration: none;">Call a doctor - (Original Mix) [~ANIMAL HOUSE MIX~]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/187724937&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/paris-saladfatt" title="Paris - (Original Mix) [ANIMAL HOUSE MIX]" target="_blank" style="color: #cccccc; text-decoration: none;">Paris - (Original Mix) [ANIMAL HOUSE MIX]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/172656960&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/dawn-original-mix" title="Dawn - (Original Mix)" target="_blank" style="color: #cccccc; text-decoration: none;">Dawn - (Original Mix)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836073&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/satelite" title="Satelite" target="_blank" style="color: #cccccc; text-decoration: none;">Satelite</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836052&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/fuckin-lights-on" title="Fuckin Lights On" target="_blank" style="color: #cccccc; text-decoration: none;">Fuckin Lights On</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/904725760&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/ice-cream-nightly" title="Ice Cream Nightly" target="_blank" style="color: #cccccc; text-decoration: none;">Ice Cream Nightly</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910839499&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/evidence" title="EVIDENCE" target="_blank" style="color: #cccccc; text-decoration: none;">EVIDENCE</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836043&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/i-know-that-i" title="I Know That I" target="_blank" style="color: #cccccc; text-decoration: none;">I Know That I</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836007&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/colours-of-my-mind" title="Colours of My Mind" target="_blank" style="color: #cccccc; text-decoration: none;">Colours of My Mind</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910835983&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/you-with-me" title="You with Me" target="_blank" style="color: #cccccc; text-decoration: none;">You with Me</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836016&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/feel-it-on-my-own" title="Feel It On My Own&#x27;" target="_blank" style="color: #cccccc; text-decoration: none;">Feel It On My Own&#x27;</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910836028&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/birthday-cakes" title="Birthday Cakes" target="_blank" style="color: #cccccc; text-decoration: none;">Birthday Cakes</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/910835995&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/engine-rev" title="Engine Rev" target="_blank" style="color: #cccccc; text-decoration: none;">Engine Rev</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/165971467&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/grave-robber-original-mix" title="Grave Robber - (Original Mix)" target="_blank" style="color: #cccccc; text-decoration: none;">Grave Robber - (Original Mix)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/163126959&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/forward-original-mix" title="Forward - (Original Mix)" target="_blank" style="color: #cccccc; text-decoration: none;">Forward - (Original Mix)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/151906956&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/flashback-calvin-harris-james-salafatinos-remix" title="Flashback - Calvin Harris [James Salafatinos Remix]" target="_blank" style="color: #cccccc; text-decoration: none;">Flashback - Calvin Harris [James Salafatinos Remix]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/149238198&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/bloom-original-mix" title="Bloom - (Original Mix)" target="_blank" style="color: #cccccc; text-decoration: none;">Bloom - (Original Mix)</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/145500629&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/over-the-hills-original-mix" title="Over The Hills- [Original Mix]" target="_blank" style="color: #cccccc; text-decoration: none;">Over The Hills- [Original Mix]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/144302627&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/into-the-sound" title="Into The Sound - [Original Mix]" target="_blank" style="color: #cccccc; text-decoration: none;">Into The Sound - [Original Mix]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/138457860&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/baja-dingus-3000-the-return-1" title="Baja Dingus 3000 (The RETURN) - [Original Mix]" target="_blank" style="color: #cccccc; text-decoration: none;">Baja Dingus 3000 (The RETURN) - [Original Mix]</a></div>`,
            `<iframe width="200%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/120468578&color=%23ff5500&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/firesurgery" title="Fire Surgery" target="_blank" style="color: #cccccc; text-decoration: none;">Fire Surgery</a> · <a href="https://soundcloud.com/firesurgery/rhino-original-mix" title="Rhino - [Original Mix]" target="_blank" style="color: #cccccc; text-decoration: none;">Rhino - [Original Mix]</a></div>`,
        ]


        let frameScale = new THREE.Vector3(.1, .1, .1)

        const frameDiv = document.createElement('div');
        // frameDiv.className = 'label';
        frameDiv.innerHTML = html[htmlIdx];
        // frameDiv.style.marginTop = '-1em';
        const frameLabel = new CSS3DObject(frameDiv);
        frameLabel.scale.set(frameScale.x, frameScale.y, frameScale.z)
        // console.log('frameLabel', frameLabel)
        frameLabel.position.set(_x, _y, _z);
        frameLabel.position.x = -1
        frameLabel.position.y = 17
        frameLabel.position.z = -4

        mesh.add(frameLabel);
        this.label_meshes.push(mesh)

        this.scene.add(mesh)
        // labels.push(frameLabel)

        this.isPlaying = true;
        return mesh
    }

    createLight() {
        let light = new THREE.PointLight(0xff0000, 1, 100)
        light.position.set(this.mesh.position.x, this.mesh.position.y, this.mesh.position.z);
        this.light = light
        this.scene.add(light)
        this.isLit = true;

    }
    update() {
        this.mesh.rotation.x += .015 + Math.random() / 100
        this.mesh.rotation.y += 0 + Math.random() / 10

    }

}





export { SoundStation }